woowacourse-teams/2022-smody

- frontend/src/components/ChallengeItem/index.tsx
- frontend/src/components/ChallengeItem/type.ts
- frontend/src/components/ChallengeList/ChallengeList.stories.tsx
- frontend/src/components/ChallengeList/index.tsx
- frontend/src/components/ChallengeList/type.ts
- frontend/src/components/Header/index.tsx
- frontend/src/components/Header/useHeader.ts
- frontend/src/components/InfiniteScroll/index.tsx
- frontend/src/components/InfiniteScroll/type.ts
- frontend/src/components/Input/index.tsx
- frontend/src/components/Input/useInput.ts
- frontend/src/components/LandingNavigation/index.tsx
- frontend/src/components/LandingNavigation/type.ts
- frontend/src/components/LoadingButton/index.tsx
- frontend/src/components/LoadingSpinner/index.tsx
- frontend/src/components/Logo/index.tsx
- frontend/src/components/Navbar/index.tsx
- frontend/src/components/Navbar/useNavBar.ts
- frontend/src/components/PrivateOutlet/index.tsx
- frontend/src/components/PrivateOutlet/type.ts
- frontend/src/components/index.ts
- frontend/src/pages/SearchPage/index.tsx
- frontend/src/pages/SearchPage/useSearchPage.ts
close #126 
1. 기존 ChallengeList 컴포넌트에 있는 코드를 SearchPage로 이동. 추가적으로 ChallengeList 컴포넌트는 주입받은 배열 데이터를 map 하는 역할로 수정
2. LoadingButton, PrivateOutlet, LadingNavigation 컴포넌트에 삼항연사자 대신 Early Return 적용
> refactor: 컴포넌트에서 UI 로직을 페이지 커스텀훅으로 분리(2)

- frontend/src/pushStatus.ts
close #267 
다음 함수의 반환값이 false이면 Notification 객체를 호출하지 않도록 변경
```javascript
const isSupported = () =>
'Notification' in window && 'serviceWorker' in navigator && 'PushManager' in window;
```
> fix: ios에서 Notification Api가 없음에 따른 에러 해결

- frontend/src/pages/CertPage/index.tsx
- CertPage에서 도전 중인 챌린지가 없을 때 빈 화면 대신 EmptyContent 컴포넌트를 렌더링하도록 수정
> fix: (fe) 도전 중인 챌린지가 없을 때 CertPage에 EmptyContent 렌더링

- frontend/src/components/CustomCycleTimeBottomSheet/index.tsx
- frontend/src/components/UnderLineText/index.tsx
시작 시간 선택 bottom sheet에서 챌린지 이름을 나타내는 ui 변경
> design: (fe) challengeName을 underline으로 표시

- frontend/src/apis/oAuthApi/type.ts
- frontend/src/pages/ProfileEditPage/index.tsx
close #325 
refetch 문제는 해결했으나, 다음과 같은 이슈를 확인했습니다.
`프로필 이미지(POST)`와 `닉네임과 자기소개(PATCH)` 수정 요청을 함께 보내면, 
성공 응답은 다 오지만,
refetch한 프로필 정보에는 수정된 `닉네임과 자기소개`이 반영되어 있지 않습니다.
백엔드 동시성 문제로 추측됩니다. 관련해서 이슈를 만들겠습니다.
> fix: 프로필 편집 완료 후 refetch되지 않던 문제 해결

- frontend/public/manifest.json
- frontend/public/pushServiceWorker.js
- frontend/src/components/Header/useHeader.ts
close #285 
서비스 워커는 워커 맥락에서 실행되기 때문에 DOM에 접근할 수 없다.
따라서 메인스레드와 Web Worker는 메시지 방식으로 서로 통신하며 데이터를 주고받는다.
이 둘이 통신하기 위해서는 특별한 방법이 필요하다. 
리서치한 결과, 이번 프로젝트에서는 BroadcastChannel API 를 사용했다.
이를 이용하여 서비스워커에서 push 이벤트 감지하면 app 내에서 setAppBadge 메서드를 실행하도록 했다.
> feat: web-push 알림 받으면 setAppBadge하도록 서비스워커 통신 활성화

- backend/smody/src/main/java/com/woowacourse/smody/service/FeedQueryService.java
- before: CycleDetail 테이블에 cursorId에 맞는 id가 없을 경우 404 에러를 반환
- after: 피드 조회 시 id가 없어도 빈 리스트를 반환하도록 수정
> fix : (be) 피드 조회 시 cursorId가 0으로 올 때 발생하는 에러 처리

- frontend/src/Layout/index.tsx
- frontend/src/components/ScrollToTop/index.tsx
- frontend/src/components/ScrollToTop/type.ts
- frontend/src/components/index.ts
close #367 
> 참고 https://kimchanjung.github.io/programming/2020/06/25/react-scroll-top/
> feat: 페이지 이동시 스크롤을 상단으로 초기화

- frontend/src/components/CommentItem/index.tsx
- frontend/src/components/FeedItem/index.tsx
- frontend/src/mocks/data.ts
cloes #381 
FeedItem 컴포넌트의 피드 description(내용)을 보여주는 태그의 스타일에 아래의 속성과 값 적용
- white-space: pre-wrap;
- word-wrap: break-word;
- word-break: break-all;
추가적으로 CommentItem 컴포넌트의 content(내용)을 보여주는 태그의 스타일에 `white-space: pre-wrap` 적용
[MDN - white space](https://developer.mozilla.org/ko/docs/Web/CSS/white-space)
> fix: (fe) 피드와 댓글 UI에서 텍스트 넘치는 이슈 해결

- frontend/src/components/CommentInput/index.tsx
- frontend/src/components/CycleDetailItem/index.tsx
- frontend/src/components/FeedItem/index.tsx
- frontend/src/components/FeedItem/type.ts
- frontend/src/components/FeedItem/useFeedItem.ts
- frontend/src/mocks/data.ts
- frontend/src/pages/FeedDetailPage/index.tsx
- frontend/src/pages/FeedPage/index.tsx
close #380 
FeedItem의 ChallengeName 스타일드 컴포넌트에 `pointer-events: auto` 스타일 추가했습니다. 이로인해 부모의 `pointer-events` 값에 관계없이 ChallengeName은 포인터 이벤트의 대상이 될 수 있습니다.
[MDN pointer-events](https://developer.mozilla.org/ko/docs/Web/CSS/pointer-events)
<br>
`상쾌한 하루의 시작, 미라클 모닝!` 챌린지 이름을 피드 페이지에서는 요약해서 보이고, 피드 상세 페이지에서는 전체 이름을 보여주도록 구현했습니다.
FeedItem 컴포넌트에 isShowBriefChallengeName Props를 추가했습니다. isShowBriefChallengeName Props에 따라 챌린지 이름의 요약 여부를 결정하도록 구현했습니다.
> fix: (fe) 피드 상세 페이지에서 챌린지 이름 관련 이슈 해결

- frontend/src/components/CycleDetailItem/index.tsx
CycleDetailItem의 description이 잘렸을 때 스크롤로 나오게 구현
> fix: (fe) CycleDetailItem description 잘림 문제 해결

- frontend/src/commonType.ts
- frontend/src/components/FeedItem/index.tsx
- frontend/src/components/FeedItem/type.ts
- frontend/src/components/FeedItem/useFeedItem.ts
- frontend/src/mocks/data.ts
- frontend/src/pages/FeedDetailPage/index.tsx
- CheckCircles 추가
- 성공한 cycle일 때
- 왕관 추가
- 테두리 추가
> feat: (fe) 피드 페이지에서 progressCount 정보 추가

- backend/smody/src/main/java/com/woowacourse/smody/cycle/repository/CycleRepository.java
Close #398 
원인 : 위에서 제시한 원인과 더불어, 실제 원인은 `for share` 공유락은 해당 레코드를 조회하는 것은 상관없으나,
update에 대해서는 해당 요청이 대기하기 때문에 발생하였다. 또한 사이클 상태 변경에 있어서
하나의 트랜잭션에 최초 조회 시 공유락과 함께 update 쿼리가 같이 존재하기 때문에 복수의 트랜잭션 발생 시
데드락이 발생함을 확인함
해결 : 더 엄격한 조건의 `PESSIMISTIC_WRITE` 락으로 수정
> hotfix : 같은 계정의 복수 기기 접속 시 발생하는 db deadlock문제 해결

- backend/smody/src/main/java/com/woowacourse/smody/cycle/repository/DynamicCycleRepositoryImpl.java
- backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleRepositoryTest.java
- backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
```
private Expression<Long> successCountSubQuery() {
QCycle subCycle = new QCycle("subCycle");
return ExpressionUtils.as(
JPAExpressions.select(count(subCycle.id))
.from(subCycle)
.where(new BooleanBuilder()
.and(subCycle.challenge.eq(cycle.challenge))
.and(subCycle.progress.eq(Progress.SUCCESS))
.and(subCycle.member.eq(cycle.member))
),
"successCount");
}
```
성공 횟수를 세는 서브 쿼리에서 member에 대한 필터링이 빠져 있었음
> fix: (be) 진행 중인 사이클에서 성공횟수 오류 수정

- frontend/src/components/@shared/ModalOverlay/index.tsx
- frontend/src/components/@shared/ModalOverlay/type.ts
- frontend/src/components/BottomSheet/index.tsx
- frontend/src/components/BottomSheet/type.ts
- frontend/src/components/Dropdown/index.tsx
- frontend/src/components/Dropdown/type.ts
- frontend/src/components/ErrorBoundary/index.tsx
- frontend/src/components/ErrorBoundary/type.ts
- frontend/src/components/InfiniteScroll/index.tsx
- frontend/src/components/InfiniteScroll/type.ts
- frontend/src/components/LinkText/index.tsx
- frontend/src/components/LinkText/type.ts
- frontend/src/components/ScrollToTop/index.tsx
- frontend/src/components/ScrollToTop/type.ts
- frontend/src/components/Title/index.tsx
- frontend/src/components/Title/type.ts
close #410 
팀의 타입스크립트 컨벤션에 맞게 children이 사용된 컴포넌트의 경우 props의 타입을 PropsWithChildren 유틸 타입으로 wrapping해서 사용하도록 리팩터링 진행
> refactor: (fe) children이 사용된 컴포넌트에 PropsWithChildren 적용

- backend/smody/src/main/java/com/woowacourse/smody/ranking/controller/RankingPeriodController.java
- backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/Duration.java
- backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankingPeriod.java
- backend/smody/src/main/java/com/woowacourse/smody/ranking/dto/RankingPeriodResponse.java
- backend/smody/src/main/java/com/woowacourse/smody/ranking/repository/RankingPeriodRepository.java
- backend/smody/src/main/java/com/woowacourse/smody/ranking/service/RankingPeriodService.java
- backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/AdminSecurityConfig.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/ChallengePushEventIntegrationTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/ChallengePushEventListenerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerIntegrationTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/EventExceptionTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventIntegrationTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventListenerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/ranking/controller/RankingControllerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/ranking/service/RankingPeriodServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/support/ControllerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/support/IntegrationTest.java
#458 
- RankingPeriod 관련 domain, repository, service, controller 클래스 구현
- RankingPeriod의 전체 조회 로직 구현
- StartDate 기준으로 내림차순 정렬
```sql
select
rankingper0_.ranking_period_id as ranking_1_7_,
rankingper0_.duration as duration2_7_,
rankingper0_.start_date as start_da3_7_ 
from
ranking_period rankingper0_ 
order by
rankingper0_.start_date desc
```
> feat : (be) 랭킹의 기간 조회

- frontend/public/pwaServiceWorker.js
- frontend/src/components/NotificationMessage/useNotificationMessage.ts
카카오톡 인앱 브라우저 등 서비스워커가 지원되지 않는 곳에서 해당 기능을 사용하지 않도록 한다
> hotfix: 카카오톡 인앱 브라우저 등 기타 브라우저의 에러 해결

- backend/smody/src/main/java/com/woowacourse/smody/push/PushScheduler.java
- backend/smody/src/main/java/com/woowacourse/smody/push/event/CommentPushEventListener.java
- backend/smody/src/main/java/com/woowacourse/smody/push/event/SubscriptionPushEventListener.java
- backend/smody/src/main/java/com/woowacourse/smody/push/repository/PushNotificationRepository.java
- backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
- backend/smody/src/test/java/com/woowacourse/smody/push/PushSchedulerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerIntegrationTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventIntegrationTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/SubscriptionPushEventListenerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationServiceTest.java
close #508 
각 EventListener 클래스에서는 알림의 저장까지만 수행함
> refactor: (be) 알림 api 전송 scheduler에게 위임 밎 update n+1 해결 

- backend/smody/src/main/java/com/woowacourse/smody/config/TomcatWebCustomConfig.java
```text
java.lang.IllegalArgumentException: Invalid character found in the request target [/challenges?filter=[ ]. The valid characters are defined in RFC 7230 and RFC 3986
```
- https://dev-jwblog.tistory.com/49
스프링 부트에서 사용하는 내장 톰캣이 특정 버전 이상에서는 RFC 3986 규격을 사용합니다.
> [HTTP/1.1 사양](https://tools.ietf.org/rfc/rfc7230.txt) 에서는 URI 쿼리 문자열에 사용할 때 특정 문자가 %nn 인코딩되도록 요구합니다. 불행히도 모든 주요 브라우저를 포함한 많은 사용자 에이전트는 이 사양을 준수하지 않고 이러한 문자를 인코딩되지 않은 형태로 사용합니다. Tomcat이 이러한 요청을 거부하는 것을 방지하기 위해 이 속성을 사용하여 허용할 추가 문자를 지정할 수 있습니다. 지정하지 않으면 추가 문자가 허용되지 않습니다. 값은 다음 문자의 조합일 수 있습니다 " < > [ \ ] ^ ` { | }. . 값에 있는 다른 모든 문자는 무시됩니다.
```java
package com.woowacourse.smody.config;
import org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory;
import …
```
> fix : (be) 챌린지 조회할 때 `[, ]`로 검색 시 에러 해결

- backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
- backend/smody/src/main/java/com/woowacourse/smody/config/WebPushSchedulerConfig.java
- backend/smody/src/main/java/com/woowacourse/smody/push/WebPushBatch.java
- backend/smody/src/main/java/com/woowacourse/smody/push/WebPushScheduler.java
- backend/smody/src/main/java/com/woowacourse/smody/push/WebPushSchedulerConfig.java
- backend/smody/src/test/java/com/woowacourse/smody/push/WebPushBatchTest.java
`java -jar -Dspring.profiles.active=prod -Dbatch.schedule.enabled=true smody-0.0.1-SNAPSHOT.jar`
`java -jar -Dspring.profiles.active=prod smody-0.0.1-SNAPSHOT.jar
`
`batch.schedule.enabled=true`일 때만 스케줄러 빈이 등록되도록 구현
`batch.schedule.enabled` 값이 없으면 자동으로 스케줄러가 안돌도록 동작
> feat: (be) n대의 WAS에서 스케줄러 가동 여부 유연하게 결정 구현

- backend/smody/src/main/java/com/woowacourse/smody/challenge/domain/ChallengingRecords.java
- backend/smody/src/main/java/com/woowacourse/smody/challenge/repository/DynamicChallengeRepositoryImpl.java
- backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
- backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeService.java
- backend/smody/src/main/java/com/woowacourse/smody/cycle/repository/CycleRepository.java
- backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
- backend/smody/src/main/java/com/woowacourse/smody/db_support/CursorPaging.java
- backend/smody/src/main/java/com/woowacourse/smody/db_support/PagingParams.java
- backend/smody/src/main/java/com/woowacourse/smody/db_support/SortSelection.java
- backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
- backend/smody/src/test/java/com/woowacourse/smody/challenge/repository/ChallengeRepositoryTest.java
- backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
#556
- 임의의 챌린지를 조회
- 현재 진행중인 참가자 순으로 조회
> feat : (be) 챌린지 필터링 기능 구현

- backend/smody/src/main/java/com/woowacourse/smody/comment/domain/Comment.java
- backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/Cycle.java
- backend/smody/src/main/java/com/woowacourse/smody/cycle/domain/CycleDetail.java
- backend/smody/src/main/java/com/woowacourse/smody/member/service/MemberService.java
- backend/smody/src/main/java/com/woowacourse/smody/push/WebPushBatch.java
- backend/smody/src/main/java/com/woowacourse/smody/push/domain/PushNotification.java
- backend/smody/src/main/java/com/woowacourse/smody/push/domain/PushSubscription.java
- backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankingActivity.java
- backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberApiServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
#533
회원 탈퇴를 할 때 외래키 제약조건으로 인해 정상적으로 동작하지 않았다.
- Cycle을 삭제할 때 `@Modify`로 하게 되면 영속성 컨텍스트를 거치지 않고 바로 쿼리가 날라가  데이터베이스에서 `CycleDetail`에 외래키 제약조건 예외가 발생한다.
Member와 연관관계가 있는 테이블에 cascade 제약조건을 추가한다.
```java
public class Cycle {
@JoinColumn(name = "member_id")
@ManyToOne(fetch = FetchType.LAZY)
@OnDelete(action = OnDeleteAction.CASCADE) // ddl에 cascade delete 제약조건 추가
private Member member;
```
```sql
ALTER TABLE cycle
ADD CONSTRAINT FK_CYCLE_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE CASCADE;
```
다른 엔티티에도 동일하게 적용한다.
```java
// MemberService
@Transactional
public void withdraw(Long memberId) {
Member member = search(memberId);
memberRepository.delete(member); // member를 삭제하면 database의 cascade delete로 연관된 데이터를 삭제해준다.
}
```
- Member를 삭제하면 삭제되는 데이터: Cycle, CycleDetail, …
> fix :  (be) 회원 탈퇴 시 외래키 제약조건 에러 수정

- backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
- backend/smody/src/main/java/com/woowacourse/smody/push/WebPushBatch.java
- backend/smody/src/main/java/com/woowacourse/smody/push/api/WebPushApi.java
- backend/smody/src/main/java/com/woowacourse/smody/push/controller/PushSubscriptionController.java
- backend/smody/src/main/java/com/woowacourse/smody/push/event/ChallengePushEventListener.java
- backend/smody/src/main/java/com/woowacourse/smody/push/repository/PushNotificationRepository.java
- backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
- backend/smody/src/main/java/com/woowacourse/smody/push/service/PushSubscriptionApiService.java
- backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeApiServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/challenge/service/ChallengeServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberApiServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/WebPushBatchTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/controller/PushSubscriptionControllerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/event/CommentPushEventListenerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationApiServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/push/service/PushSubscriptionServiceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/support/ControllerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/support/IntegrationTest.java
전체적으로 테스트에 대한 컨벤션을 아래와 같이 작성했습니다.
- 하나의 메서드에 테스트가 하나이면 테스트 메서드 이름을 동일하게 유지하고 작성한다.
- 테스트가 2개라면 Nested를 사용하여 class 이름을 테스트할 메서드 이름과 동일하게 유지하고 테스트 메서드는 케이스별로 작성한다.
- deleteById 를 할 때 id를 찾지 못하는 경우 예외  처리
- `ExceptionData.NOT_FOUND_PUSH_NOTIFICATION`
```java
@Transactional
public void deleteById(Long pushNotificationId) {
try {
pushNotificationRepository.deleteById(pushNotificationId);
} catch (EmptyResultDataAccessException e) {
throw new BusinessException(ExceptionData.NOT_FOUND_PUSH_NOTIFICATION);
}
}
```
> test : (be) Member, Challenge, Push 도메인 서비스 계층 테스트 추가

- frontend/src/components/@shared/ModalOverlay/index.tsx
- frontend/src/components/@shared/ModalOverlay/type.ts
- frontend/src/components/FeedItem/index.tsx
- frontend/src/components/FeedItem/type.ts
- frontend/src/mocks/data.ts
- 문제점: 현재 이미지를 정사각형으로 보여주어 정사각형 나머지 영역은 화면에 보이지 않음. 특히 세로로 매우 긴 이미지를 올리는 사용자들이 늘어남에 따라 관련 컴플레인 예상
- 해결: 피드 상세보기 페이지에서만 height를 100%로 변경하여 세로로 긴 이미지를 올리는 경우에 대응, 피드 모아보기 페이지에는 영향 없음
> feat: (fe) feedItem이 피드 상세 페이지일 경우 이미지 높이를 100%로 변경하여 모두 보기

- backend/smody/src/main/java/com/woowacourse/smody/challenge/controller/ChallengeController.java
- backend/smody/src/main/java/com/woowacourse/smody/challenge/repository/ChallengeRepository.java
- backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeApiService.java
- backend/smody/src/main/java/com/woowacourse/smody/challenge/service/ChallengeService.java
- backend/smody/src/main/java/com/woowacourse/smody/exception/ControllerAdvice.java
- backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
- backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionUtils.java
- backend/smody/src/main/java/com/woowacourse/smody/exception/api/GithubApi.java
- mysql 에서는 기존 무작위 챌린지를 조회하던 쿼리가 실행되지 않았던 문제
- 모든 챌린지들의 아이디를 조회해서 정해진 만큼 무작위로 고른 다음 해당 챌린지들을 다시 조회하는 방식으로 무작위를 구현하였다.
- 예상치 못한 에러가 발생했을 때 http response 로 200 ok 를 응답하는 문제
- 예상치 못한 에러가 발생했을 때 깃허브 이슈로 해당 에러를 등록한 뒤 500 에러와 함께 해당 에러 로그를 response body 에 담아서 응답하도록 로직을 변경하였다.
> refactor: (be) 챌린지 추천 로직, 예상치 못한 에러에 대한 처리 로직 변경

- frontend/public/pwaServiceWorker.js
- frontend/src/apis/challengeApi/index.ts
- frontend/src/components/SubscriptionButton/useSubscriptionButton.ts
- frontend/src/mocks/handlers/challenge.js
- frontend/src/pages/ChallengePage/index.tsx
- frontend/src/pages/RandomChallengePage/index.tsx
- ![image](https://user-images.githubusercontent.com/70249108/196862306-956557de-77de-4757-b22a-2ad1bf86eb32.png)
> feat: (fe) 탭과 알림 모두 삭제에서 refetch가 안되는 에러

- frontend/src/components/CheckCircles/index.tsx
- frontend/src/components/DarkModeButton/index.tsx
- frontend/src/components/Input/index.tsx
- frontend/src/components/Input/type.ts
- frontend/src/components/Navbar/index.tsx
- frontend/src/components/SROnly/index.tsx
- frontend/src/components/SuccessModal/index.tsx
- frontend/src/components/Tabs/index.tsx
- frontend/src/components/Tabs/type.ts
- frontend/src/components/index.ts
- frontend/src/pages/ChallengePage/index.tsx
- frontend/src/pages/EventPage/index.tsx
- frontend/src/pages/FeedPage/index.tsx
- frontend/src/pages/PopularChallengePage/index.tsx
- frontend/src/pages/RandomChallengePage/index.tsx
- frontend/src/pages/SearchPage/index.tsx
DarkModeButton 버튼과 CheckCircles 컴포넌트에서 
`[aria-*] attributes do not match their roles` 문제가 발생했다.
해당 문제는 요소에 적용된 role에 부적절한 aria-* 속성을 사용할 때 발생하는 문제이다.
해당 문제를 해결하기 위한 해결 방법은 다음과 같다.
1. 부적절한 aria-* 속성 제거
2. 태그의 role 수정
내브바를 스크린리더로 읽을 때 `바닥글`이라고만 읽어주는 문제가 있었다. 또한 스크린리더의 내브바 내부의 각 탭 버튼 또한 적절히 읽어주지 않았다. aria-label 속성을 적절하게 사용해서 해당 문제를 해결했다.
스크린리더로 챌린지 페이지의 내용(Layout 컴포넌트의 Outlet 부분)을 포커스했을 때, 해당 페이지의 컨텐츠를 전부 읽어주는 문제가 발생했다.
따라서 aria-label을 적절히 사용해서 해당 문제를 해결했다.
또한 챌린지 페이지의 각 탭 페이지(ex. PopularChallengePage)에 section 태그와 h1 태그를 적용하여 웹 표준을 준수하도록 했다.
기존에 모달 컴포넌트에 포커스 하기 위해 focus() 메서드를 사용했다.
하지만, 다시 테스트를 수행한 결과 해당 기능이 동작하지 않은 게 확인됐다.
따라서 focus() 메서드와 함께 tabIndex 속성을 함께 사용해서 문제를 해결했다.
> feature: (fe) 웹 접근성 추가 개선

- backend/smody/src/main/java/com/woowacourse/smody/cycle/dto/ProgressResponse.java
- backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleApiService.java
- backend/smody/src/main/java/com/woowacourse/smody/cycle/service/CycleService.java
- backend/smody/src/main/resources/static/docs/api.html
- backend/smody/src/test/java/com/woowacourse/smody/acceptance/CycleAcceptanceTest.java
- backend/smody/src/test/java/com/woowacourse/smody/cycle/controller/CycleControllerTest.java
- backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleApiServiceTest.java
챌린지 인증 시 (피드 작성 시)에도 맨션을 하고 싶다는 요구가 들어왔어요. 기존에 있던 맨션 api를 사용하면 되는 문제지만 그러려면 pathId로 cycleDetailId가 필요합니다.
기존의 사이클 진척도 증가 api의 응답으로는 주고 있지 않던 정보라서 추가하기로 했습니다.
그래서 다음과 같이 반영했습니다.
그런데 이렇게 하니 cycleDetailId가 null인 현상이 발생했습니다. 일반적인 insert 문이라면 바로 SQL을 날려 id를 받아왔을 것입니다. 하지만 우리는 `CycleDetail`을 영속성 전이로 저장하고 있습니다. (`Cascade.PERSIST`) 영속성 전이로 발생한 저장은 `flush()` 시점에 쿼리가 날아가기 때문에 DTO를 세팅하는 저 시점은 `flush()` 전이라 id가 null인 것입니다.
강제적인 `flush()` 호출이 필요했습니다. 그런데 기존의 `CycleApiService`에서는 `EntityManager`나 `CycleRepository`가 없어 추가적인 의존이 필요한 상황입니다. 그래서 원래 `CycleRepository`를 가지고 있는 `CycleService`가 `flush()`를 해주도록 `increaseProgress()` 메서드를 `CycleService`가 하도록 변경했습니다.
리뷰 잘 부탁드립니다!
> feat: (be) 사이클 진척도 증가시 cycleDetailId 추가

- frontend/src/components/Navbar/index.tsx
- frontend/src/pages/ChallengePage/index.tsx
- frontend/src/pages/EventPage/index.tsx
close #648
- 추천 -> 인기 -> 검색 -> 우테코 챌린지
> feat: (fe) 챌린지 페이지 탭 순서 변경
