woowacourse-teams/2022-smody

backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
frontend/package.json

close #23
- package.json 파일에 프록시 설정
- 스프링 부트에 CORD 설정

feat: 스프링부트, 리액트 어플리케이션 로컬 연결 구현

---

frontend/src/pages/ChallengeDetailPage/index.tsx

fix: (fe) 챌린지 사이클의 잘못된 시작 시간 수정 

---

README.md

docs: 기술스택 아이콘 추가

---

frontend/src/components/Timer/index.tsx
frontend/src/components/Timer/useTimer.tsx
frontend/src/constants/domain.ts
frontend/src/mocks/data.ts

feat:  (fe) 인증 완료 후 남은 시간 표시 방법 변경

---

backend/smody/src/main/java/com/woowacourse/smody/auth/AuthInterceptor.java
backend/smody/src/main/java/com/woowacourse/smody/auth/JwtTokenExtractor.java
backend/smody/src/main/java/com/woowacourse/smody/auth/JwtTokenProvider.java
backend/smody/src/main/java/com/woowacourse/smody/controller/CycleController.java
backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengeResponse.java
backend/smody/src/main/java/com/woowacourse/smody/repository/CycleRepository.java
backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java

refactor: (be) 프로덕션 코드 리팩토링

---

backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
backend/smody/src/main/java/com/woowacourse/smody/domain/Progress.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
backend/smody/src/test/java/com/woowacourse/smody/domain/CycleTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java

feat: (be) 재도전 로직 구현

---

backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
backend/smody/src/main/java/com/woowacourse/smody/controller/CycleController.java
backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
backend/smody/src/main/java/com/woowacourse/smody/domain/Progress.java
backend/smody/src/main/java/com/woowacourse/smody/dto/StatResponse.java
backend/smody/src/main/java/com/woowacourse/smody/dto/SuccessChallengeResponse.java
backend/smody/src/main/java/com/woowacourse/smody/repository/CycleRepository.java
backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
backend/smody/src/main/java/com/woowacourse/smody/util/PagingUtil.java
backend/smody/src/main/resources/application.properties
backend/smody/src/test/java/com/woowacourse/smody/controller/ChallengeControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/CycleControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/MemberControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/domain/CycleTest.java
backend/smody/src/test/java/com/woowacourse/smody/repository/CycleRepositoryTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/ChallengeServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
backend/smody/src/test/resources/application.properties

feat: (be) 성공한 챌린지 조회 및 사이클 통계 정보 구현

---

backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
backend/smody/src/test/java/com/woowacourse/smody/domain/CycleTest.java

refactor: (be) Cycle 마감 시간 급한 순으로 정렬하는 로직 리팩터링

---

backend/smody/src/main/java/com/woowacourse/smody/controller/OauthController.java
backend/smody/src/main/java/com/woowacourse/smody/controller/openapi/GoogleApi.java
backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/MemberControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/OauthControllerTest.java

refactor: (be) 구글 api 기능 분리 및 OAuthController 테스트

---

backend/smody/.gitignore
backend/smody/gradle/wrapper/gradle-wrapper.properties

chore: (be) gitignore 수정

---

backend/smody/src/main/java/com/woowacourse/smody/controller/openapi/GoogleApi.java

fix: OAuth redirect_uri 변경

---

frontend/.gitignore
frontend/package.json
frontend/src/apis/apiClient.ts
frontend/src/constants/path.ts
frontend/src/mocks/handlers/challenge.js
frontend/webpack.config.js
frontend/yarn.lock

feat: (fe) BASE_URL 은닉화 기능 추가

---

backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
backend/smody/src/main/java/com/woowacourse/smody/dto/ChallengeResponse.java
backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
backend/smody/src/test/java/com/woowacourse/smody/controller/ChallengeControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/ChallengeServiceTest.java

feat : (be) 챌린지 단건 조회, 전체 챌린지 조회 시 도전중인지 알려주는 기능 또는 분기 처리

---

frontend/package.json
frontend/src/components/CertUnAuth/index.tsx
frontend/src/components/Header/index.tsx

fix: (fe) oAuth redirection url을 백엔드에서 바로 받는 것으로 수정

---

backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
backend/smody/src/main/java/com/woowacourse/smody/domain/Cycle.java
backend/smody/src/main/java/com/woowacourse/smody/dto/CycleRequest.java
backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java

refactor: (be) 서버 기준시간 설정 및 시간관리 통합

---

frontend/src/apis/cycleApi/api.ts
frontend/src/apis/cycleApi/type.ts
frontend/src/components/CardGridContainer/index.tsx
frontend/src/components/SuccessModal/index.tsx
frontend/src/hooks/api/usePostJoinChallenge.ts
frontend/src/mocks/data.ts
frontend/src/mocks/handlers/auth.js
frontend/src/mocks/handlers/challenge.js
frontend/src/mocks/handlers/index.ts

close #89 
Co-authored-by: Woo seung woose28@users.noreply.github.com

fix: (fe) 시간 및 성공 챌린지 에러 수정

---

frontend/src/Layout/index.tsx
frontend/src/components/ChallengeItem/index.tsx
frontend/src/components/ChallengeList/index.tsx
frontend/src/components/LoadingSpinner/index.tsx
frontend/src/components/SnackBar/index.tsx
frontend/src/components/SuccessModal/index.tsx
frontend/src/hooks/api/usePostJoinChallenge.ts
frontend/src/hooks/useIntersect.ts
frontend/src/mocks/handlers/challenge.js
frontend/src/pages/ChallengeDetailPage/index.tsx

커스텀 훅 분리 리팩토링 필요
Co-authored-by: ronci [ronci@users.noreply.github.com](mailto:ronci@users.noreply.github.com)

feat: (fe) 무한 스크롤 기능 구현

---

frontend/src/apis/challengeApi/index.ts
frontend/src/components/ChallengeList/index.tsx
frontend/src/hooks/useManageAccessToken.ts

fix: (fe) 챌린지 목록 페이지 새로고침 시 '도전중'이 풀리는 상태 수정

---

frontend/src/components/ChallengeItem/index.tsx
frontend/src/components/SuccessModal/index.tsx
frontend/src/hooks/api/type.ts
frontend/src/hooks/api/usePostJoinChallenge.ts

fix: (fe) 재도전했을 때 재도전한 챌린지가 바로 보이지 않는 에러

---

backend/smody/src/docs/asciidoc/api.adoc
backend/smody/src/main/java/com/woowacourse/smody/config/WebConfig.java
backend/smody/src/main/java/com/woowacourse/smody/controller/ChallengeController.java
backend/smody/src/main/java/com/woowacourse/smody/controller/CycleController.java
backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeQueryService.java
backend/smody/src/main/java/com/woowacourse/smody/service/ChallengeService.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleQueryService.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
backend/smody/src/main/java/com/woowacourse/smody/service/MemberService.java
backend/smody/src/main/java/com/woowacourse/smody/ui/admin/AdminSecurityConfig.java
backend/smody/src/main/resources/static/docs/api.html
backend/smody/src/test/java/com/woowacourse/smody/controller/ChallengeControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/CycleControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/MemberControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/ChallengeServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
backend/smody/yarn.lock

feat: (be) Service 계층 CQS 리팩터링

---

frontend/src/mocks/data.ts
frontend/src/mocks/handlers/auth.js
frontend/src/mocks/handlers/challenge.js
frontend/src/pages/ChallengeDetailPage/index.tsx
frontend/webpack.config.js

close #147 
추가한 API mocking 목록
- 구글 링크 조회
- 토큰 조회
- 모든 챌린지 조회(비회원)
- 챌린지 하나 상세 조회
❗️구글 링크 조회 API가 Mocking되면서 Google Client Key를 env로 관리하고 있습니다. 따라서 env 파일에 아래의 값이 추가돼야 합니다.
```
CLIENT_ID = 671293991399-in1m6ggna174bmmvjti10rjg4o85o609.apps.googleusercontent.com
```

feat: (fe) MSW API mocking 추가

---

frontend/src/pages/LandingPage/index.tsx

fix: (fe) 로그인 후 Home에서 로그인 버튼 보이는 문제 해결

---

frontend/src/components/@shared/ModalOverlay/index.tsx
frontend/src/components/Profile/index.tsx
frontend/src/components/SuccessModal/index.tsx
frontend/src/components/UserWithdrawalModal/index.tsx
frontend/src/components/UserWithdrawalModal/type.ts
frontend/src/components/index.ts
frontend/src/pages/ProfileEditPage/index.tsx

feat: (fe) 회원 탈퇴 모달 구현

---

frontend/package.json
frontend/src/App.tsx
frontend/src/Router.tsx
frontend/src/apis/oAuthApi/api.ts
frontend/src/apis/oAuthApi/index.ts
frontend/src/components/@shared/Button/index.tsx
frontend/src/components/Header/index.tsx
frontend/src/components/Input/index.tsx
frontend/src/components/SuccessModal/index.tsx
frontend/src/components/ToggleButton/ToggleButton.stories.tsx
frontend/src/components/ToggleButton/index.tsx
frontend/src/components/ToggleButton/type.ts
frontend/src/components/index.ts
frontend/src/hooks/useImageInput.tsx
frontend/src/mocks/handlers/auth.js
frontend/src/pages/LandingPage/index.tsx
frontend/src/pages/ProfileEditPage/index.tsx
frontend/src/pages/ProfilePage/index.tsx
frontend/src/recoil/darkMode/atoms.ts
frontend/src/styles/color.ts
frontend/src/styles/styled.d.ts
frontend/src/styles/theme.ts
frontend/src/utils/index.ts
frontend/yarn.lock

close #133 
- 사용자 os 다크모드 설정을 감지하여 다크모드 기본값 설정
- 토글버튼 위치 고민 필요(현재 헤더에 위치)
- 더 나은 다크모드 색상 선택 고민 필요 
> 참고 : https://ppss.kr/archives/221678
-  다크모드 적용한 UI

feat: (fe)다크모드 토글 버튼 기능 구현

---

frontend/package.json
frontend/src/Layout/index.tsx
frontend/src/apis/cycleApi/api.ts
frontend/src/apis/cycleApi/index.ts
frontend/src/components/@shared/Button/index.tsx
frontend/src/components/CardGridContainer/index.tsx
frontend/src/components/ChallengeItem/index.tsx
frontend/src/components/Profile/index.tsx
frontend/src/hooks/auth/useAuth.ts
frontend/src/pages/CertPage/index.tsx
frontend/src/pages/ChallengeDetailPage/index.tsx
frontend/src/pages/Feed/index.tsx
frontend/src/pages/LandingPage/index.tsx
frontend/src/pages/NotFoundPage/index.tsx
frontend/src/pages/ProfileEditPage/index.tsx
frontend/src/pages/ProfilePage/index.tsx
frontend/src/pages/SearchPage/index.tsx
frontend/src/pages/VocPage/index.tsx
frontend/src/pages/index.tsx
frontend/src/queryClient.ts
frontend/src/styles/color.ts
frontend/src/styles/theme.ts
frontend/yarn.lock

- react18의 suspense를 적용하여 로딩 UI를 구현한다

feat: (fe) 로딩 로직 구현 및 UI 적용

---

frontend/src/Layout/index.tsx
frontend/src/components/@shared/FlexBox/type.ts
frontend/src/components/CardBox/index.tsx
frontend/src/components/CertItem/index.tsx
frontend/src/components/ChallengeItem/index.tsx
frontend/src/components/ChallengeList/index.tsx
frontend/src/components/CheckCircles/index.tsx
frontend/src/components/EmptyContent/index.tsx
frontend/src/components/Header/index.tsx
frontend/src/components/Navbar/index.tsx
frontend/src/components/Profile/index.tsx
frontend/src/components/SnackBar/index.tsx
frontend/src/components/SuccessModal/index.tsx
frontend/src/components/Timer/index.tsx
frontend/src/components/UserWithdrawalModal/index.tsx
frontend/src/pages/ChallengeDetailPage/index.tsx
frontend/src/pages/LandingPage/index.tsx
frontend/src/pages/ProfileEditPage/index.tsx
frontend/src/pages/ProfilePage/index.tsx
frontend/src/pages/VocPage/index.tsx

close #123 
- 각 props의 타입을 CSSProperties에서 Pick 하는 대신 uion 타입으로 선언

refactor: (fe) FlexBox 컴포넌트 타입 수정

---

frontend/src/pages/ProfileEditPage/index.tsx

fix: (fe) 프로필 이미지 수정 후 새로 바뀐 이미지가 바로 안보이는 문제 해결

---

frontend/src/components/SuccessModal/index.tsx
frontend/src/mocks/handlers/challenge.js
frontend/src/pages/CertFormPage/index.tsx
frontend/src/pages/CertFormPage/type.ts

feat: (fe) 인증하기 페이지 추가 기능 구현

---

frontend/src/hooks/useAuth.ts

close #60 
구글 OAuth로그 인 후 url 남아있는 code 제거하는 기능 구현

feat: (fe) google oAuth 로그인 시 url에 code 지우는 기능 구현

---

frontend/src/Layout/index.tsx
frontend/src/Layout/type.ts
frontend/src/components/@shared/ModalOverlay/index.tsx
frontend/src/components/FixedButton/index.tsx
frontend/src/components/Header/index.tsx
frontend/src/components/Navbar/index.tsx
frontend/src/components/SnackBar/index.tsx
frontend/src/components/UnderLineText/index.tsx
frontend/src/constants/css.ts

fix: (fe) Header와 Navbar CSS 문제 해결

---

backend/smody/src/main/java/com/woowacourse/smody/repository/CycleRepository.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
backend/smody/src/test/resources/data.sql

fix : (be) 글과 사진으로 인증 시 동시성 이슈 해결

---

frontend/src/assets/loading_dots.svg
frontend/src/components/LoadingButton/LoadingButton.stories.tsx
frontend/src/components/LoadingButton/index.tsx
frontend/src/components/LoadingButton/type.ts
frontend/src/components/index.ts
frontend/src/mocks/handlers/auth.js
frontend/src/mocks/handlers/challenge.js
frontend/src/pages/CertFormPage/index.tsx
frontend/src/pages/ChallengeDetailPage/index.tsx
frontend/src/pages/ProfileEditPage/index.tsx

feat: (fe) LoadingButton 컴포넌트 구현

---

frontend/src/Router.tsx
frontend/src/components/CertItem/index.tsx
frontend/src/constants/path.ts
frontend/src/pages/CertFormPage/index.tsx
frontend/src/pages/CertFormPage/type.ts

close #199 
useLocation의 state 이용

feat: (fe) CertForm 접근 경로 제거

---

frontend/src/pages/CertFormPage/index.tsx

- 기록에 아무 값도 입력되지 않았을 때
- 기록에 빈 공백만 입력됐을 때
ex. `OOO챌린지 n번째 완료`

fix: (fe) 인증 시 description 기본 값 전달하도록 수정

---

frontend/src/components/Profile/index.tsx
frontend/src/components/Profile/useProfile.ts
frontend/src/components/SuccessModal/index.tsx
frontend/src/components/SuccessModal/type.ts
frontend/src/components/SuccessModal/useSuccessModal.ts
frontend/src/components/Timer/index.tsx
frontend/src/components/Title/index.tsx
frontend/src/components/Title/type.ts
frontend/src/components/Title/useTitle.ts
frontend/src/components/UserWithdrawalModal/index.tsx
frontend/src/components/UserWithdrawalModal/type.ts
frontend/src/components/UserWithdrawalModal/useUserWithdrawalModal.ts
frontend/src/pages/CertFormPage/index.tsx
frontend/src/pages/CertFormPage/useCertFormPage.ts
frontend/src/pages/CertPage/index.tsx
frontend/src/pages/CertPage/useCertPage.ts

close #126 
CertFormPage, CertPage, Profile, SuccessModal, Title, UserWithdrawalModal, VisiblityIcon 
컴포넌트들의 개별 커스텀훅을 분리

refactor: (fe) 컴포넌트에서 UI 로직을 페이지 커스텀훅으로 분리(1)

---

frontend/src/apis/challengeApi/api.ts
frontend/src/apis/challengeApi/index.ts
frontend/src/apis/challengeApi/type.ts
frontend/src/components/ChallengeList/index.tsx
frontend/src/components/ChallengeList/type.ts
frontend/src/components/Navbar/index.tsx
frontend/src/components/SearchBar/SearchBar.stories.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/components/SearchBar/type.ts
frontend/src/components/index.ts
frontend/src/hooks/useInput.ts
frontend/src/mocks/handlers/challenge.js
frontend/src/pages/ProfileEditPage/index.tsx
frontend/src/pages/SearchPage/index.tsx
frontend/src/pages/SearchPage/useSearchPage.ts

feat: (fe) 챌린지 검색 기능 구현

---

frontend/src/Router.tsx
frontend/src/apis/constants.ts
frontend/src/apis/feedApi/api.ts
frontend/src/apis/feedApi/index.ts
frontend/src/apis/feedApi/type.ts
frontend/src/commonType.ts
frontend/src/components/Comment/Comment.stories.tsx
frontend/src/components/Comment/index.tsx
frontend/src/components/CommentInput/CommentInput.stories.tsx
frontend/src/components/CommentInput/index.tsx
frontend/src/components/CommentInput/type.ts
frontend/src/components/CommentInput/useCommentInput.ts
frontend/src/components/CommentItem/CommentItem.stories.tsx
frontend/src/components/CommentItem/index.tsx
frontend/src/components/CommentItem/type.ts
frontend/src/components/FeedItem/index.tsx
frontend/src/components/FeedItem/type.ts
frontend/src/components/FeedItem/useFeedItem.ts
frontend/src/components/index.ts
frontend/src/constants/domain.ts
frontend/src/constants/path.ts
frontend/src/mocks/data.ts
frontend/src/mocks/handlers/feed.js
frontend/src/pages/CertFormPage/index.tsx
frontend/src/pages/FeedDetailPage/index.tsx
frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts
frontend/src/pages/index.tsx
frontend/src/styles/GlobalStyle.ts

feat: (fe) 댓글 컴포넌트 개발 및 피드 상세보기 페이지 API 연결

---

frontend/package.json
frontend/src/index.tsx
frontend/webpack.config.js

close #271 
- script:local 명령어 추가
- local의 BASE_URL은 development와 같으나, msw는 실행되지 않는다.

feat: (fe) script 실행 명령어 추가

---

frontend/src/components/@shared/Button/index.tsx
frontend/src/components/FixedButton/index.tsx
frontend/src/components/SnackBar/index.tsx

feat: (fe) FixedButton과 Snackbar 겹침 해결

---

frontend/src/components/@shared/Button/index.tsx
frontend/src/components/FixedButton/index.tsx
frontend/src/components/Header/index.tsx
frontend/src/components/SnackBar/index.tsx
frontend/src/components/SubscriptionButton/index.tsx
frontend/src/push/badge.js

- Badging Api 사용
- https://w3c.github.io/badging/

feat: (fe) App의 알림 개수 Badge 표시

---

frontend/src/pages/SearchPage/useSearchPage.ts

fix: (fe) 챌린지 검색 시 발생하는 에러 해결

---

backend/smody/src/docs/asciidoc/api.adoc
backend/smody/src/main/java/com/woowacourse/smody/SmodyApplication.java
backend/smody/src/main/java/com/woowacourse/smody/controller/CommentController.java
backend/smody/src/main/java/com/woowacourse/smody/domain/AuditingEntity.java
backend/smody/src/main/java/com/woowacourse/smody/domain/Comment.java
backend/smody/src/main/java/com/woowacourse/smody/domain/CycleDetail.java
backend/smody/src/main/java/com/woowacourse/smody/domain/Feed.java
backend/smody/src/main/java/com/woowacourse/smody/dto/CommentResponse.java
backend/smody/src/main/java/com/woowacourse/smody/dto/CommentUpdateRequest.java
backend/smody/src/main/java/com/woowacourse/smody/dto/FeedResponse.java
backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionData.java
backend/smody/src/main/java/com/woowacourse/smody/repository/CommentRepository.java
backend/smody/src/main/java/com/woowacourse/smody/repository/FeedRepository.java
backend/smody/src/main/java/com/woowacourse/smody/service/CommentQueryService.java
backend/smody/src/main/java/com/woowacourse/smody/service/CommentService.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
backend/smody/src/main/java/com/woowacourse/smody/service/FeedQueryService.java
backend/smody/src/main/java/com/woowacourse/smody/service/FeedService.java
backend/smody/src/main/java/com/woowacourse/smody/ui/admin/controller/AdminSecurityConfig.java
backend/smody/src/test/java/com/woowacourse/smody/ResourceFixture.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/AcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/CommentAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/CommentControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/controller/ControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/domain/CommentTest.java
backend/smody/src/test/java/com/woowacourse/smody/repository/CycleDetailRepositoryTest.java
backend/smody/src/test/java/com/woowacourse/smody/repository/FeedRepositoryTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/CommentQueryServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/CommentServiceTest.java

- 댓글 생성
- 댓글 조회
- 피드 조회 시 댓글 개수와 함께 조회
- 댓글 수정
- 댓글 삭제

feat : (be) 댓글 기능 구현

---

frontend/src/assets/share_icon.svg
frontend/src/components/@shared/Button/index.tsx
frontend/src/components/ChallengeDetail/index.tsx
frontend/src/components/ChallengeDetail/type.ts
frontend/src/components/FixedButton/index.tsx
frontend/src/components/ShareButton/index.tsx
frontend/src/components/Title/index.tsx
frontend/src/components/Title/type.ts
frontend/src/components/index.ts
frontend/src/pages/ChallengeDetailPage/index.tsx
frontend/src/pages/CycleDetailPage/index.tsx

close #304 
- 우측 상단의 공유 버튼 및 기능 추가

feat: (fe) 페이지 공유 기능 추가

---

frontend/src/components/@shared/Text/index.tsx
frontend/src/components/ChallengeItem/index.tsx
frontend/src/components/Challenger/index.tsx
frontend/src/components/CycleDetailItem/index.tsx
frontend/src/components/FeedItem/index.tsx
frontend/src/components/SuccessModal/useSuccessModal.ts
frontend/src/pages/FeedPage/index.tsx

feat: (fe) Feed에 반응형 디자인 적용(grid)

---

frontend/webpack.config.js

- 웹팩 설정에 추가
```javascript
new CopyWebpackPlugin({
patterns: [
{ from: 'public/image', to: 'image' },
{ from: 'public/manifest.json', to: '.' },
{ from: 'public/pushServiceWorker.js', to: '.' },
],
}),
```

feat: (fe) 웹팩 빌드 시 public 폴더 내 파일들을 복사하여 dist 폴더에 넣기

---

frontend/src/components/FeedItem/index.tsx

design: (fe) Feed UI 수정 

---

backend/smody/src/main/java/com/woowacourse/smody/domain/PushCase.java
backend/smody/src/main/java/com/woowacourse/smody/push/strategy/CommentPushStrategy.java
backend/smody/src/main/java/com/woowacourse/smody/service/CommentService.java
backend/smody/src/main/java/com/woowacourse/smody/service/CycleService.java
backend/smody/src/test/java/com/woowacourse/smody/ResourceFixture.java
backend/smody/src/test/java/com/woowacourse/smody/push/PushSchedulerTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventListenerTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/strategy/ChallengePushStrategyTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/strategy/CommentPushStrategyTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/strategy/SubscriptionPushStrategyTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/CycleServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/service/PushSubscriptionServiceTest.java

feat: (be) 댓글이 달렸을 때 알림 전송 기능 구현

---

backend/smody/src/main/java/com/woowacourse/smody/push/strategy/CommentPushStrategy.java
backend/smody/src/main/resources/static/docs/api.html
backend/smody/src/test/java/com/woowacourse/smody/push/event/PushEventListenerTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/strategy/CommentPushStrategyTest.java

CommentPushStrategy에
```
if (comment.getMember() == cycleDetailWriter) {
return;
}
```
추가

feature:(be) 자신의 피드에 댓글을 달면 알림 저장 안되도록 구현

---

backend/smody/src/main/java/com/woowacourse/smody/domain/Member.java
backend/smody/src/test/java/com/woowacourse/smody/service/MemberServiceTest.java

fix: (be) Member에 변경감지 필터링 적용

---

frontend/src/apis/challengeApi/api.ts
frontend/src/apis/challengeApi/index.ts
frontend/src/apis/challengeApi/type.ts
frontend/src/apis/constants.ts
frontend/src/apis/cycleApi/api.ts
frontend/src/apis/cycleApi/type.ts
frontend/src/components/CardBox/index.tsx
frontend/src/components/CardBox/type.ts
frontend/src/components/CardGridContainer/index.tsx
frontend/src/components/CardGridContainer/useCardGridContainer.ts

feat: (fe) 프로필에서 진행중인 챌린지 UI 및 수정된 API 연결 

---

frontend/src/Layout/index.tsx
frontend/src/apis/oAuthApi/index.ts
frontend/src/components/CardBox/index.tsx
frontend/src/components/CardGridContainer/useCardGridContainer.ts
frontend/src/components/CertItem/index.tsx
frontend/src/components/CertItem/useCertItem.ts
frontend/src/components/ChallengeItem/index.tsx
frontend/src/components/ChallengerList/useChallengerList.ts
frontend/src/components/CommentItem/index.tsx
frontend/src/components/CustomCycleTimeBottomSheet/index.tsx
frontend/src/components/CycleDetailItem/index.tsx
frontend/src/components/CycleDetailList/index.tsx
frontend/src/components/FeedItem/index.tsx
frontend/src/components/Profile/index.tsx
frontend/src/pages/CertPage/useCertPage.ts
frontend/src/pages/ChallengeDetailPage/useChallengeDetailPage.ts
frontend/src/pages/CycleDetailPage/useCycleDetailPage.ts
frontend/src/pages/FeedDetailPage/index.tsx
frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts
frontend/src/pages/FeedPage/useFeedPage.ts
frontend/src/pages/SearchPage/useSearchPage.ts
frontend/src/queryClient.ts
frontend/src/styles/theme.ts
frontend/src/utils/validator.ts

feat: QA 피드백 UI 반영

---

frontend/src/apis/cycleApi/api.ts
frontend/src/apis/cycleApi/index.ts
frontend/src/apis/cycleApi/type.ts
frontend/src/components/CycleRecords/index.tsx
frontend/src/components/CycleRecords/type.ts
frontend/src/components/CycleRecords/useCycleRecordList.ts
frontend/src/components/CycleRecords/useCycleRecords.ts

feat: (fe) 챌린지에 대한 내 사이클 상세보기 페이지에서 전체, 성공 필터 버튼 구현

---

frontend/src/components/ChallengeItem/index.tsx
frontend/src/components/Title/index.tsx
frontend/src/pages/CycleDetailPage/index.tsx

feat: 추가적인 디자인 수정

---

frontend/src/apis/pushNotificationApi/api.ts
frontend/src/hooks/useSubscribe.ts

fix: (fe) unsubscribe api 에러 해결

---

frontend/src/Layout/index.tsx
frontend/src/components/Header/index.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/pages/SearchPage/index.tsx

feat: (fe) header와 search-bar 디자인 변경

---

backend/smody/build.gradle

chore : perforMon관련 의존성 추가

---

frontend/public/pwaServiceWorker.js

refactor: (fe) 서비스워커 오프라인 관련 코드 리팩터링

---

frontend/src/components/CommentInput/index.tsx
frontend/src/components/FeedItem/index.tsx

- conflict를 해결 중 #385 pr의 작업 내용이 누락돼서 다시 커밋했습니다([27809ef](27809efcfcbaa0aeef2e85163dfea6822f45d243))
- @ronci  [필요 없는 패딩 스타일 제거 피드백](https://github.com/woowacourse-teams/2022-smody/pull/385#discussion_r965457972) 반영했습니다!([dff1eb4](dff1eb4ce50cf61d56463113afa6ad41404e5fa4))

fix: (fe) 피드 상세 페이지 챌린지 이름 관련 누락된 코드 반영

---

frontend/src/components/ChallengeItem/index.tsx
frontend/src/components/ChallengeList/index.tsx
frontend/src/components/SearchBar/SearchBar.stories.tsx
frontend/src/components/SearchBar/index.tsx
frontend/src/components/SearchBar/type.ts
frontend/src/constants/domain.ts
frontend/src/constants/regex.ts
frontend/src/hooks/useDebounce.ts
frontend/src/hooks/useSnackBar.ts
frontend/src/pages/SearchPage/index.tsx
frontend/src/pages/SearchPage/useSearchPage.ts

cloes #324 #394 
해당 브랜치에서 새로운 기능 구현 및 최적화 작업을 같이 진행했습니다.
작업 목록은 다음과 같습니다.
- 검색 페이지에서 검샘어를 입력하면 `모든 챌린지 조회` API가 호출되도록 구현했습니다. [37d9dae](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/37d9daed877acde9b2bb5c292cd027dada332c81)
- debounce를 적용하여 API 요청 횟수를 최적화했습니다.
- 이에따라 SearchBar 컴포넌트에 사용되던 form 태그를 div 태그로 변경했습니다. [60d6642](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/60d66423489a88229a47ffcca5545c47e4a2d8ac)
- 검색 아이콘을 눌렀을 때는 여전히 API 요청이 가도록 구현했습니다.
- 검색어 입력 시 검색 페이지의  렌더링를 최적화 시키기 위해 input 컴포넌트를 비제어 컴포넌트로 변경했습니다. [631c52f](https://github.com/woowacourse-teams/2022-smody/pull/395/commits/631c52f7b64f526115cf99d9376e544d97c1d55d)
최적화 테스트 조건은 다음과 같습니다.
1. 성능 측전 전 챌린지1과 챌린지2가 미리 생성돼 있어야한다.
2. 검색 페이지에서 챌린지1을 검색한다.
3. 검색 페이지에서 챌린지를 검색한다.
4. 검색 페이지에서 빈 키워드로 …

feat: (fe) 챌린지 이름 입력 시 자동 검색되는 기능 구현

---

frontend/public/pwaServiceWorker.js
frontend/src/components/CardGridContainer/useCardGridContainer.ts
frontend/src/pages/CertPage/useCertPage.ts
frontend/src/pages/FeedPage/useFeedPage.ts
frontend/src/pages/SearchPage/useSearchPage.ts
frontend/src/pwa/indexedDB.js

```javascript
indexedDB.clearPost('myChallenge').then(() => {
for (const myChallenge of myChallenges) {
indexedDB.savePost('myChallenge', myChallenge);
}
});
```
- 위와 같은 코드의 패턴이 반복되어, 이를 리팩터링하고자 함
- 따라서 indexedDB 클래스 내부에 putPost 메서드를 추가하고 위 코드를 putPost 메서드로 대체함
```javascript
putPost = (name, dataList) => {
this.clearPost(name).then(() => {
for (const data of dataList) {
this.savePost(name, data);
}
});
};
```
```javascript
indexedDB.putPost('myChallenge', myChallenges);
```

refactor: (fe) indexedDB 클래스에 putPost 메서드 추가하여 리팩터링

---

frontend/public/pwaServiceWorker.js

close #417
HTMLCanvas에 서비스워커로부터 받은 opaque response 이미지를 전달할 때, Canvas가 CORS 에러를 발생시킴. 따라서 캐싱된 이미지를 오프라인에서만 사용하도록 하는 Network First 전략으로 변경함으로써, opaque response가 되지 않도록 하여 해결한다.

fix: (fe) 이미지 캐싱 전략을 Cache First에서 Network First로 변경

---

frontend/public/pwaServiceWorker.js
frontend/src/components/ErrorBoundary/index.tsx
frontend/src/pages/CertPage/index.tsx
frontend/src/pages/FeedPage/index.tsx
frontend/src/pages/SearchPage/index.tsx

refactor: (fe) 에러바운더리 리팩터링 및 네트워크 에러 시 스낵바

---

frontend/src/hooks/useAuth.ts
frontend/src/mocks/handlers/auth.js

close # 430
- 로그인 후 피드 페이지로 이동하도록 수정

fix: (fe) 로그인 후 리다이렉션되는 url 변경

---

frontend/src/components/FeedItem/index.tsx
frontend/src/hooks/useImageInput.tsx

feat: (fe) progressImage 레이지 로딩 제거 및 이미지 압축률 올리기

---

frontend/public/pwaServiceWorker.js
frontend/src/components/NotificationMessage/useNotificationMessage.ts

기존 BroadcastChannel API는 ios 15 미만에서 작동하지 않아서, 호환성이 더 좋은 MessageChannel API로 변경

fix: (fe) MessageChannel API로 변경

---

frontend/src/components/CardGridContainer/useCardGridContainer.ts
frontend/src/pwa/indexedDB.js

fix: 사용하지 않는 myChallenge 관련 indexedDB 코드 삭제

---

frontend/src/components/CardGridContainer/useCardGridContainer.ts
frontend/src/pwa/indexedDB.js

fix: (fe) 사용하지 않는 myChallenge 관련 indexedDB 코드 삭제 (#442)

Version 3.1.1 배포 

---

frontend/public/pwaServiceWorker.js
frontend/src/App.tsx
frontend/src/components/CardGridContainer/useCardGridContainer.ts
frontend/src/pwa/indexedDB.js

fix: (fe) refetch 하면서 indexedDB 중복저장하던 문제 해결

---

backend/smody/src/main/java/com/woowacourse/smody/cycle/repository/DynamicCycleRepositoryImpl.java
frontend/public/pwaServiceWorker.js
frontend/src/App.tsx
frontend/src/components/CardGridContainer/useCardGridContainer.ts
frontend/src/pwa/indexedDB.js

fix: (fe) refetch 하면서 indexedDB 중복저장하던 문제 해결 #446

Version 3.1.2 배포

---

frontend/public/pwaServiceWorker.js
frontend/src/pages/CertPage/useCertPage.ts
frontend/src/pages/FeedPage/useFeedPage.ts
frontend/src/pages/SearchPage/useSearchPage.ts
frontend/src/pwa/indexedDB.js

fix: (fe) 검색 페이지에서 indexedDB 가 두 번 중복 호출되는 문제 해결

---

frontend/public/pwaServiceWorker.js
frontend/src/components/Challenger/index.tsx
frontend/src/components/CommentItem/index.tsx
frontend/src/components/FeedItem/index.tsx
frontend/src/components/Profile/index.tsx
frontend/src/hooks/useImageInput.tsx
frontend/src/pages/CertFormPage/index.tsx
frontend/src/pages/ProfileEditPage/index.tsx
frontend/src/pwa/indexedDB.js

close #452 
프로필 이미지 비율을 유지하기 위해 object-fit cover 추가

refactor: (fe) 이미지 압축 훅에서 압축률 옵션을 매개변수로 분리

---

frontend/src/constants/storage.ts
frontend/src/pages/CertPage/useCertPage.ts
frontend/src/pages/FeedPage/useFeedPage.ts
frontend/src/pages/SearchPage/useSearchPage.ts
frontend/src/pwa/indexedDB.js

storage.ts에 다음과 같이 indexedDB name들을 분리
```ts
export const INDEXED_DB_NAME = 'smody-db';
export const INDEXED_DB = {
FEED: 'feed',
CYCLE: 'cycle',
CHALLENGE: 'challenge',
};
```

feat: (fe) indexedDB의 name들을 constants로 분리

---

backend/smody/src/main/java/com/woowacourse/smody/member/controller/MemberController.java
backend/smody/src/main/java/com/woowacourse/smody/member/dto/MentionResponse.java
backend/smody/src/main/java/com/woowacourse/smody/member/repository/DynamicMemberRepository.java
backend/smody/src/main/java/com/woowacourse/smody/member/repository/DynamicMemberRepositoryImpl.java
backend/smody/src/main/java/com/woowacourse/smody/member/repository/MemberRepository.java
backend/smody/src/main/java/com/woowacourse/smody/member/service/MemberService.java
backend/smody/src/main/resources/static/docs/api.html
backend/smody/src/test/java/com/woowacourse/smody/member/controller/MemberControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/support/ResourceFixture.java

feat : (be) 멘션 시 대응되는 사용자들의 목록을 가져오는 기능 구현

---

frontend/src/apis/constants.ts
frontend/src/apis/rankingApi/api.ts
frontend/src/apis/rankingApi/index.ts
frontend/src/apis/rankingApi/type.ts
frontend/src/components/Navbar/index.tsx
frontend/src/components/RankingItem/index.tsx
frontend/src/components/RankingItem/type.ts
frontend/src/components/RankingPeriodItem/index.tsx
frontend/src/components/RankingPeriodsList/index.tsx
frontend/src/components/RankingPeriodsList/type.ts
frontend/src/components/RankingPeriodsList/useRankingPeriodsList.ts
frontend/src/components/UserRanking/index.tsx
frontend/src/components/UserRanking/type.ts
frontend/src/components/UserRanking/useUserRanking.ts
frontend/src/components/index.ts
frontend/src/mocks/data.ts
frontend/src/mocks/handlers/ranking.js
frontend/src/pages/RankingPage/index.tsx
frontend/src/pages/RankingPage/type.ts
frontend/src/pages/RankingPage/useRankingPage.ts
frontend/src/types/ranking.ts

feat: (fe) 랭킹 페이지에서 나의 랭킹 구현

---

frontend/src/components/RankingItem/index.tsx
frontend/src/components/UserRanking/index.tsx
frontend/src/components/UserRanking/useUserRanking.ts
frontend/src/constants/domain.ts
frontend/src/mocks/handlers/ranking.js
frontend/src/pages/RankingPage/useRankingPage.ts

feat: (fe) 나의 랭킹에서 기간에 대한 정보가 오기 전까지 API 요청 막기 및 다른 상태에 따른 UI Skeleton 구현

---

frontend/src/components/RankingItem/index.tsx
frontend/src/components/RankingItem/type.ts
frontend/src/components/RankingItem/useRankingItem.ts
frontend/src/components/RankingList/index.tsx
frontend/src/components/RankingList/useRankingList.tsx
frontend/src/components/RankingPeriodItem/index.tsx
frontend/src/components/RankingPeriodItem/useRankingPeriodItem.ts
frontend/src/components/RankingPeriodsList/index.tsx
frontend/src/components/RankingPeriodsList/useRankingPeriodsList.ts
frontend/src/components/UserRanking/index.tsx
frontend/src/pages/RankingPage/index.tsx
frontend/src/utils/index.ts

feat: (fe) 랭킹 페이지 디자인 수정

---

frontend/src/components/RankingList/index.tsx
frontend/src/components/RankingList/useRankingList.tsx
frontend/src/components/RankingPeriodItem/index.tsx
frontend/src/components/RankingPeriodsList/index.tsx
frontend/src/components/RankingPeriodsList/useRankingPeriodsList.ts
frontend/src/components/UserRanking/useUserRanking.ts
frontend/src/constants/domain.ts
frontend/src/mocks/data.ts
frontend/src/utils/index.ts

feat: (fe) 랭킹 기간 데이터에 따른 UI 변화 구현

---

frontend/public/pwaServiceWorker.js
frontend/src/components/CommentInput/index.tsx
frontend/src/components/CommentInput/useCommentInput.ts
frontend/src/components/NotificationMessage/useNotificationMessage.ts
frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts

fix: 댓글 수정 시 기존 댓글 내용 가져오기, 알림 리다이렉션

---

frontend/src/components/CardBox/index.tsx
frontend/src/components/CardGridContainer/index.tsx
frontend/src/components/RankingPeriodItem/index.tsx
frontend/src/components/RankingPeriodsList/index.tsx
frontend/src/components/UserRanking/index.tsx

feat: (fe) 랭킹, 참가한 챌린지 디자인 변경

---

frontend/public/pwaServiceWorker.js
frontend/src/components/ChallengeList/index.tsx
frontend/src/components/FeedItem/index.tsx
frontend/src/components/FeedItem/useFeedItem.ts
frontend/src/components/Title/index.tsx
frontend/src/components/Title/useTitle.ts
frontend/src/constants/css.ts
frontend/src/hooks/useScrollDirection.ts
frontend/src/pages/ChallengeDetailPage/index.tsx
frontend/src/pages/FeedDetailPage/index.tsx

feat: (fe) 피드 상세보기 스크롤 시 NavBar 위치 자동 조절

---

frontend/src/components/RankingPeriodItem/useRankingPeriodItem.ts

feat: (fe) 랭킹 기간 리스트 표기 수정

---

frontend/public/pwaServiceWorker.js
frontend/src/utils/index.ts

fix: (fe) 랭킹 기간 계산 이슈 해결

---

frontend/src/components/CommentInput/index.tsx
frontend/src/components/CommentInput/useCommentInput.ts
frontend/src/components/CommentInput/useMention.ts
frontend/src/components/CommentInput/usePopover.ts
frontend/src/hooks/useMutationObserver.ts

refactor: (fe) 멘션 기능 파일 분리 및 리팩터링

---

frontend/src/assets/plus.svg
frontend/src/components/Navbar/index.tsx

feat: (fe) 네비게이션의 인증 버튼을 flat하게 변경한다

---

frontend/src/components/CommentInput/index.tsx
frontend/src/components/CommentInput/useCommentInput.ts

feat: (fe) 댓글에 공백이나 개행문만 입력하여 전송하면 발생하는 에러 해결

---

frontend/src/pages/CertFormPage/index.tsx
frontend/src/pages/CertFormPage/useCertFormPage.ts

feat: (fe) 모바일에서 인증형식이 가려지는 에러 및 인증 페이지의 스크롤 통일

---

frontend/src/components/RankingItem/index.tsx
frontend/src/mocks/data.ts

feat: (fe) 랭킹 등수, 포인트에 따른 레이아웃 변경 수정

---

backend/smody/src/docs/asciidoc/api.adoc
backend/smody/src/main/java/com/woowacourse/smody/push/controller/PushNotificationController.java
backend/smody/src/main/java/com/woowacourse/smody/push/repository/PushNotificationRepository.java
backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationApiService.java
backend/smody/src/main/java/com/woowacourse/smody/push/service/PushNotificationService.java
backend/smody/src/main/resources/static/docs/api.html
backend/smody/src/test/java/com/woowacourse/smody/push/controller/PushNotificationControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationApiServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationServiceTest.java

보낸 알림 모두 삭제
```json
DELETE /push-notifications/me
Authorization: Bearer ${accessToken}
```
```json
204 NoContent
```

feature: (be) 나의 보낸 알림 모두 삭제 기능 구현

---

frontend/public/pwaServiceWorker.js
frontend/src/pages/EventPage/index.tsx

`챌린지를 1회라도 인증한다면 추첨을 통해 스모디 컵을 드립니다!`라는 설명 추가

feat: (fe) 이벤트 챌린지 설명 추가

---

frontend/public/pwaServiceWorker.js
frontend/src/pages/EventPage/index.tsx

Version 4.1.1 배포

---

frontend/src/pages/ChallengePage/index.tsx

feat: (fe) contentPage에 suspense 추가

---

frontend/public/pwaServiceWorker.js
frontend/src/constants/event.ts

feat: (fe) 이벤트 챌린지 2개 추가

---

frontend/src/Router.tsx
frontend/src/apis/challengeApi/api.ts
frontend/src/apis/challengeApi/index.ts
frontend/src/apis/challengeApi/type.ts
frontend/src/components/ErrorBoundary/index.tsx
frontend/src/constants/path.ts
frontend/src/constants/storage.ts
frontend/src/pages/ChallengePage/index.tsx
frontend/src/pages/PopularChallengePage/index.tsx
frontend/src/pages/PopularChallengePage/usePopularChallengePage.ts
frontend/src/pages/RandomChallengePage/index.tsx
frontend/src/pages/RandomChallengePage/useRandomChallengePage.ts
frontend/src/pages/index.tsx
frontend/src/pwa/indexedDB.js

인기, 랜덤 모두 default size인 10개씩 출력되도록 했다.

feat: (fe) 챌린지 정렬 방법 추가

---

frontend/src/apis/pushNotificationApi/api.ts
frontend/src/apis/pushNotificationApi/index.ts
frontend/src/components/Dropdown/index.tsx
frontend/src/components/NotificationMessage/index.tsx
frontend/src/components/SubscriptionButton/index.tsx
frontend/src/components/SubscriptionButton/useSubscriptionButton.ts
frontend/src/mocks/data.ts
frontend/src/mocks/handlers/push.js
frontend/src/pages/FeedDetailPage/useFeedDetailPage.ts

feat: (fe) 버튼을 눌렀을 때 모든 알림이 지워지도록 구현

---

frontend/src/components/CommentInput/index.tsx
frontend/src/components/Tooltip/index.tsx
frontend/src/components/Tooltip/type.ts

feat: (fe) 댓글 멘션 알림 툴팁 추가

---

frontend/public/pwaServiceWorker.js
frontend/src/Layout/index.tsx
frontend/src/pwa/indexedDB.js

hotfix: 아웃렛 아웃라인 파란선 없애기

---

frontend/public/manifest.json
frontend/public/pwaServiceWorker.js
frontend/src/components/CommentInput/usePopover.ts

fix: (fe) 멘션하고 뒤에 쓴 글을 수정하려고 지우면 전체 삭제됨 에러 해결

---

.vscode/settings.json
frontend/public/manifest.json
frontend/public/pwaServiceWorker.js
frontend/src/components/NotificationMessage/useNotificationMessage.ts

- 푸시알림 아이콘 뱃지 이미지 적용  close #571
- 미지원 브라우저에 대응한 BroadcastChannel 재적용 close #285

fix: (fe) 푸시알림 아이콘 뱃지 이미지 적용 및 미지원 브라우저에 대응한 BroadcastChannel 재적용

---

frontend/src/hooks/useAuth.ts

feat: (fe) 로그인 후 Feed 페이지로 리다이렉션 되도록 구현

---

frontend/lib/README.md
frontend/lib/package.json

close #635 
수정 전 - PickType에 대한 설명 없음
수정 후 - PickType에 대한 설명 추가

feat: (fe) Typescript Module README 수정

---

backend/smody/src/main/java/com/woowacourse/smody/challenge/controller/ChallengeController.java
backend/smody/src/main/java/com/woowacourse/smody/challenge/domain/ChallengingRecords.java
backend/smody/src/main/java/com/woowacourse/smody/comment/service/CommentService.java
backend/smody/src/main/java/com/woowacourse/smody/cycle/controller/CycleController.java
backend/smody/src/main/java/com/woowacourse/smody/exception/ExceptionUtils.java
backend/smody/src/main/java/com/woowacourse/smody/image/strategy/ImgBBImageStrategy.java
backend/smody/src/main/java/com/woowacourse/smody/ranking/domain/RankManager.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/AcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/AcceptanceTestFixture.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/ChallengeAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/CommentAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/CycleAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/FeedAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/MemberAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/OauthAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/PushAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/acceptance/RankingAcceptanceTest.java
backend/smody/src/test/java/com/woowacourse/smody/cycle/controller/CycleControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/cycle/domain/ProgressTest.java
backend/smody/src/test/java/com/woowacourse/smody/cycle/repository/CycleRepositoryTest.java
backend/smody/src/test/java/com/woowacourse/smody/cycle/service/CycleServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/exception/BindingExceptionTest.java
backend/smody/src/test/java/com/woowacourse/smody/member/controller/MemberControllerTest.java
backend/smody/src/test/java/com/woowacourse/smody/member/service/MemberApiServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/event/EventExceptionTest.java
backend/smody/src/test/java/com/woowacourse/smody/push/service/PushNotificationApiServiceTest.java
backend/smody/src/test/java/com/woowacourse/smody/ranking/event/RankingEventExceptionTest.java
backend/smody/src/test/java/com/woowacourse/smody/support/EventListenerMockTest.java

close #306 
`AcceptanceTestFixture`와 `AcceptanceTest`에 요청과 검증에 관한 공통 로직들을 세팅하고 테스트를 진행하였습니다.

test: (be) 인수 테스트 작성

---

frontend/src/hooks/useInstallApp.ts
frontend/src/pages/LandingPage/components/InstallPrompt/index.tsx
frontend/src/utils/index.ts

close https://github.com/woowacourse-teams/2022-smody/issues/642
불필요한 코드 제거
부정확한 변수명 변경
코드 제자리 찾기

refactor: (fe) useInstallApp 리팩터링(conflict 해결)

---

frontend/public/pwaServiceWorker.js

- 캐시 버스팅을 위해 serviceworker 버전 증가

feat: (fe) serviceworker 버전 업그레이드

---

.github/workflows/frontend-ci.yml
frontend/package.json
frontend/public/pwaServiceWorker.js

Version 4.3.1 배포
